spring.datasource.url=jdbc:mysql://localhost:3306/curewell
spring.datasource.username=root
spring.datasource.password=@The7Umbrellas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC


